name: Auto Merge PR if 'dependencies' label is present

on:
  pull_request:
    types:
      - labeled  # Trigger when a label is added to the PR
    branches:
      - main  # You can replace 'main' with the branch you want

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto Merge PR if 'dependencies' label is present
        uses: peter-evans/auto-merge@v2
        with:
          merge-method: merge  # You can change this to 'squash' or 'rebase' if desired
          labels: 'dependencies'  # Only auto-merge PRs with this label
