name: Auto Merge PR if 'dependencies' label is present

on:
  pull_request:
    types:
      - labeled
    branches:
      - main  # Make sure this matches the branch your PR targets

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR has 'dependencies' label and is mergeable
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr.labels.some(label => label.name === 'dependencies') && pr.mergeable_state === 'clean' && !pr.draft) {
              console.log('PR is labeled with "dependencies" and is mergeable. Proceeding with auto-merge.');
              // Auto merge PR using GitHub API
              const mergeResponse = await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: `Auto-merge PR #${pr.number}`,
                merge_method: 'merge',  // You can use 'squash' or 'rebase' if preferred
              });
              console.log('PR merged:', mergeResponse);
            } else {
              console.log('PR is not labeled with "dependencies" or is not mergeable.');
            }
      
