name: Test GitHub Actions Workflow

on:
  push:
    branches:
      - main  # This will trigger the workflow on push to the 'main' branch

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        run: echo "GitHub Actions is working!"
