name: Auto Merge PR and Delete Branch if 'dependencies' label is present

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
    branches:
      - main  # Adjust this for your default branch (e.g., 'main', 'develop', etc.)

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR has 'dependencies' label
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: echo "PR has 'dependencies' label. Proceeding with merge."

      - name: Merge PR if label is present
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete the branch after merge
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          # Delete the branch associated with the PR
          gh pr view ${{ github.event.pull_request.number }} --json headRefName -q '.headRefName' | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/{}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
